# re-enable a specific script via `package.json:dependenciesMeta:<moduleName>:built = true`
enableScripts: false

nodeLinker: node-modules
compressionLevel: mixed
enableGlobalCache: false
yarnPath: .yarn/releases/yarn-4.12.0.cjs
