import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  goldenPathSidebar: [
    "overview",
    {
      type: "category",
      label: "Profiles",
      link: { type: "doc", id: "profiles" },
      items: [{ type: "autogenerated", dirName: "profile" }],
    },
    {
      type: "category",
      label: "Practices",
      link: { type: "doc", id: "practices" },
      items: [{ type: "autogenerated", dirName: "practice" }],
    },
    {
      type: "category",
      label: "Patterns",
      link: { type: "doc", id: "patterns" },
      items: [{ type: "autogenerated", dirName: "pattern" }],
    },
    {
      type: "category",
      label: "Problems",
      link: { type: "doc", id: "problems" },
      items: [{ type: "autogenerated", dirName: "problem" }],
    },
  ],
};

export default sidebars;
