import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  goldenPathSidebar: [
    "overview",
    {
      type: "category",
      label: "Roles",
      link: { type: "doc", id: "roles" },
      items: [
        {
          type: "category",
          label: "Server",
          link: { type: "doc", id: "roles/server/index" },
          items: ["roles/server/first-party", "roles/server/third-party"],
        },
        "roles/client",
        "roles/tooling",
        "roles/schema-designer",
        "roles/application-developer",
      ],
    },
    {
      type: "category",
      label: "Practices",
      link: { type: "doc", id: "practices" },
      items: [{ type: "autogenerated", dirName: "practices" }],
    },
    {
      type: "category",
      label: "Solutions",
      link: { type: "doc", id: "solutions" },
      items: [{ type: "autogenerated", dirName: "solutions" }],
    },
    {
      type: "category",
      label: "Problems",
      link: { type: "doc", id: "problems" },
      items: [{ type: "autogenerated", dirName: "problems" }],
    },
  ],
};

export default sidebars;
