import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  goldenPathSidebar: [
    "overview",
    {
      type: "category",
      label: "Profiles",
      link: { type: "doc", id: "profiles/index" },
      items: [{ type: "autogenerated", dirName: "profiles" }],
    },
    {
      type: "category",
      label: "Practices",
      link: { type: "doc", id: "practices/index" },
      items: [{ type: "autogenerated", dirName: "practices" }],
    },
    {
      type: "category",
      label: "Patterns",
      link: { type: "doc", id: "patterns/index" },
      items: [{ type: "autogenerated", dirName: "patterns" }],
    },
    {
      type: "category",
      label: "Problems",
      link: { type: "doc", id: "problems/index" },
      items: [{ type: "autogenerated", dirName: "problems" }],
    },
  ],
};

export default sidebars;
